# Generated by Django 4.2.10 on 2024-02-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_name_listing_title_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('FD', 'Food and Drink'), ('HO', 'Home'), ('EL', 'Electronics'), ('BT', 'Books and TV'), ('FA', 'Fashion'), ('TO', 'Toys')], max_length=64, null=True),
        ),
    ]
